### ISSUE TITLE
Multilingualism Support?

### ISSUE THREAD

**Issue by bartmika** [themefisher/hargo-hugo-ecommerce-theme#20]
Hello!

Does the theme support multiple languages? If not, how can we make it support it?

Thank you,

**Comment by developer-evan** [comment]
Hey @bartmika 

Thanks for your concern, I am sorry to say that this theme does not support multi-language yet. You can follow Hugo documentation to make it multilingual, if you have knowledge about Hugo. Or you can contact us at mehedi@themefisher.com for any kind of customization [paid]
