### ISSUE TITLE
Cart icon doesn't show count

### ISSUE THREAD

**Issue by thdoan** [themefisher/hargo-hugo-ecommerce-theme#25]
I'm not sure if this is a localhost only issue or not, but here's how to reproduce:

1. `hugo new site demo`
2. `cd demo/themes`
3. `git clone git@github.com:themefisher/hargo.git`
4. Copy everything inside `demo/themes/hargo/exampleSite` to `demo` directory
5. `hugo server -D`
6. Go to http://localhost:1313/

The site looks perfect, but upon loading these JS errors were in the console:

![image](https://user-images.githubusercontent.com/4110567/99943042-81397b80-2d25-11eb-96a6-a887106ad4c3.png)

When I added a product to the cart, it's added to the cart, but the cart icon doesn't show the count. I'm not sure if this is related to the errors above.

**Comment by thdoan** [comment]
UPDATED: I fixed all the JS errors and will submit a PR soon. It was caused by two issues:

1. languageCode should be "en" not "en-us"
2. Snipcart v2 integration method was used, but linking to v3 snippet

**Comment by developer-evan** [comment]
Hey @thdoan 

I have fixed that issue, please download the latest code, and enjoy...
