### ISSUE TITLE
Strikethrough price displayed even if no discounted price

### ISSUE THREAD

**Issue by thdoan** [themefisher/hargo-hugo-ecommerce-theme#27]
Even when a product has `priceBefore: ""`, the strikethrough price is still displayed:

![image](https://user-images.githubusercontent.com/4110567/100138287-ab349000-2e42-11eb-88fc-c8602ded422a.png)

I've already fixed this in my fork, so expect a PR soon.

**Comment by developer-evan** [comment]
Hey there, Thanks for your contribution, I merged your PR.
