### ISSUE TITLE
SCSS Compiler not working

### ISSUE THREAD

**Issue by juby-gif** [themefisher/hargo-hugo-ecommerce-theme#29]
I was using your hargo theme, and i’ve done some changes in scss files. Honestly i’m just learning scss and i’d like to know how do I compile the scss so that I can see my changes on the site.

**Comment by developer-evan** [comment]
Hello @juby-gif 

Please follow this doc https://docs.gethugothemes.com/guide/#install-hugo

**Comment by juby-gif** [comment]
Hi @developer-evan 

I had installed the hugo extended one and i ran this command `hugo server -w -v --disableFastRender`. But still it's not working

**Comment by developer-evan** [comment]
Hello @juby-gif 

Did you try this procedure? https://docs.gethugothemes.com/guide/#run-theme-locally

**Comment by juby-gif** [comment]
Hello @developer-evan!

Yes i did the same procedure, but at some point the scss seems to be compiled and i got a css file. But still it's not reflected back on site.

**Comment by somratpro** [comment]
Hello @juby-gif 

Did you try to clear your browser cache?

**Comment by somratpro** [comment]
I am going to close this issue, if you face any more issue, feel free to re-open this issue, or create a new one.
